package com.ketchupzzz.isaom.presentation.main.policy

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavHostController
import com.ketchupzzz.isaom.models.PrivacyPolicy


@Composable
fun PrivacyPolicyScreen(
    modifier: Modifier = Modifier,
    navHostController: NavHostController
) {
    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(16.dp)
            .verticalScroll(rememberScrollState())
    ) {
        // Header
        Text(
            text = "Privacy Policy",
            fontSize = 24.sp,
            fontWeight = FontWeight.Bold,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        Text(
            text = "Last updated: October 10, 2024",
            fontSize = 14.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        Text(
            text = "This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Interpretation and Definitions Section
        SectionHeader("Interpretation and Definitions")

        Text(
            text = "Interpretation\n\nThe words of which the initial letter is capitalized have meanings defined under the following conditions.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        SectionHeader("Definitions")
        Text(
            text = "Account: A unique account created for You to access our Service or parts of our Service.\n" +
                    "Application: Refers to iSaom, the software program provided by the Company.\n" +
                    "Company: Refers to iSaom (referred to as either 'the Company', 'We', 'Us', or 'Our').\n" +
                    "Country: Refers to the Philippines.\n" +
                    "Device: Any device that can access the Service, such as a computer, a cellphone, or a digital tablet.\n" +
                    "Personal Data: Any information that relates to an identified or identifiable individual.\n" +
                    "Service: Refers to the Application.\n" +
                    "Service Provider: Any natural or legal person who processes the data on behalf of the Company.\n" +
                    "Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.\n" +
                    "You: The individual accessing or using the Service or the company/legal entity on behalf of which such individual is accessing the Service.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Collecting and Using Your Personal Data
        SectionHeader("Collecting and Using Your Personal Data")

        Text(
            text = "Types of Data Collected\n\nPersonal Data\n\nWhile using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You, such as your email address, first name, last name, and LRN.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        Text(
            text = "Usage Data\n\nUsage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, browser version, the pages You visit, and time spent on those pages.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Information Collected while Using the Application
        SectionHeader("Information Collected while Using the Application")
        Text(
            text = "While using Our Application, in order to provide features, we may collect with Your prior permission: Pictures and other information from your Device's camera and photo library. You can enable or disable access to this information at any time through Your Device settings.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Use of Your Personal Data
        SectionHeader("Use of Your Personal Data")
        Text(
            text = "The Company may use Personal Data for the following purposes:\n" +
                    "• To provide and maintain our Service\n" +
                    "• To manage Your Account\n" +
                    "• To contact You\n" +
                    "• To manage Your requests\n" +
                    "• For other purposes such as data analysis, identifying usage trends, and improving our Service",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Retention of Your Personal Data
        SectionHeader("Retention of Your Personal Data")
        Text(
            text = "The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Transfer of Your Personal Data
        SectionHeader("Transfer of Your Personal Data")
        Text(
            text = "Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of Your state, province, or country.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Delete Your Personal Data
        SectionHeader("Delete Your Personal Data")
        Text(
            text = "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Disclosure of Your Personal Data
        SectionHeader("Disclosure of Your Personal Data")
        Text(
            text = "Under certain circumstances, the Company may be required to disclose Your Personal Data if required by law or in response to valid requests by public authorities.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Security of Your Personal Data
        SectionHeader("Security of Your Personal Data")
        Text(
            text = "We strive to use commercially acceptable means to protect Your Personal Data, but we cannot guarantee its absolute security.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Links to Other Websites
        SectionHeader("Links to Other Websites")
        Text(
            text = "Our Service may contain links to other websites that are not operated by Us. We are not responsible for the content, privacy policies, or practices of any third-party sites or services.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Changes to this Privacy Policy
        SectionHeader("Changes to this Privacy Policy")
        Text(
            text = "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        // Contact Us
        SectionHeader("Contact Us")
        Text(
            text = "If you have any questions about this Privacy Policy, you can contact us by email: isaom.admin@gmail.com",
            fontSize = 16.sp,
            modifier = Modifier.padding(bottom = 16.dp)
        )
    }
}

@Composable
fun SectionHeader(title: String) {
    Text(
        text = title,
        fontSize = 20.sp,
        fontWeight = FontWeight.Bold,
        modifier = Modifier.padding(vertical = 8.dp)
    )
}