package com.ketchupzzz.isaom.models

 data class WordTranslate(
    val english : String,
    val ilocano : String
) {

}

fun WordTranslate.init() : List<WordTranslate>{
        val wordTranslations = listOf(
            WordTranslate("Hello", "Kablaaw"),
            WordTranslate("Thank you", "Agyamanak"),
            WordTranslate("Good morning", "Naimbag a bigat"),
            WordTranslate("Good afternoon", "Naimbag a malem"),
            WordTranslate("Good evening", "Naimbag a rabii"),
            WordTranslate("Good night", "Naimbag a rabii"),
            WordTranslate("How are you?", "Kumusta ka?"),
            WordTranslate("Please", "Masapul"),
            WordTranslate("Sorry", "Pakawanennak"),
            WordTranslate("Yes", "Wen"),
            WordTranslate("No", "Saan"),
            WordTranslate("Water", "Danum"),
            WordTranslate("Food", "Makan"),
            WordTranslate("Friend", "Gayem"),
            WordTranslate("Love", "Ayat"),
            WordTranslate("House", "Balay"),
            WordTranslate("Work", "Trabaho"),
            WordTranslate("Family", "Pamilya"),
            WordTranslate("School", "Eskwela"),
            WordTranslate("Child", "Ubing"),
            WordTranslate("Mother", "Nanang"),
            WordTranslate("Father", "Tatang"),
            WordTranslate("Brother", "Kabsat a lalaki"),
            WordTranslate("Sister", "Kabsat a babai"),
            WordTranslate("Rain", "Tudtudo"),
            WordTranslate("Sun", "Init"),
            WordTranslate("Moon", "Bulan"),
            WordTranslate("Star", "Bituen"),
            WordTranslate("Dog", "Aso"),
            WordTranslate("Cat", "Pusa"),
            WordTranslate("Fish", "Lames"),
            WordTranslate("Bird", "Gayang"),
            WordTranslate("Flower", "Sabong"),
            WordTranslate("Tree", "Kayo"),
            WordTranslate("Mountain", "Bantay"),
            WordTranslate("River", "Karayan"),
            WordTranslate("Sea", "Dagat"),
            WordTranslate("Island", "Pulo"),
            WordTranslate("Heart", "Puso"),
            WordTranslate("Life", "Biag"),
            WordTranslate("Happy", "Naragsak"),
            WordTranslate("Sad", "Nalakneng"),
            WordTranslate("Angry", "Agbuteng"),
            WordTranslate("Sleep", "Turog"),
            WordTranslate("Wake up", "Agriing"),
            WordTranslate("Eat", "Mangan"),
            WordTranslate("Drink", "Uminom"),
            WordTranslate("Read", "Basa"),
            WordTranslate("Write", "Surat"),
            WordTranslate("Walk", "Lukmeg"),
            WordTranslate("Run", "Dardaras"),
            WordTranslate("Jump", "Luksu"),
            WordTranslate("Sing", "Kantaan"),
            WordTranslate("Dance", "Sadsa"),
            WordTranslate("Play", "Ay-ayatek"),
            WordTranslate("Study", "Agbasbasa"),
            WordTranslate("Teach", "Ituturo"),
            WordTranslate("Learn", "Agadal"),
            WordTranslate("Beautiful", "Nasantuan"),
            WordTranslate("Handsome", "Nasilingan"),
            WordTranslate("Big", "Dakkel"),
            WordTranslate("Small", "Babaet"),
            WordTranslate("Hot", "Napudot"),
            WordTranslate("Cold", "Nalamiis"),
            WordTranslate("Tall", "Natayag"),
            WordTranslate("Short", "Nababa"),
            WordTranslate("Heavy", "Nabangsit"),
            WordTranslate("Light", "Nababassit"),
            WordTranslate("Strong", "Nabaknang"),
            WordTranslate("Weak", "Nalaka"),
            WordTranslate("New", "Baro"),
            WordTranslate("Old", "Daang"),
            WordTranslate("Rich", "Nabaknang"),
            WordTranslate("Poor", "Nasadut"),
            WordTranslate("Fast", "Napigsa"),
            WordTranslate("Slow", "Nagmalmalem"),
            WordTranslate("Near", "Padaya"),
            WordTranslate("Far", "Adayo"),
            WordTranslate("Early", "Nasapa"),
            WordTranslate("Late", "Natayag"),
            WordTranslate("High", "Napuskol"),
            WordTranslate("Low", "Nakinnababa"),
            WordTranslate("Left", "Lukoy"),
            WordTranslate("Right", "Wadayat"),
            WordTranslate("Open", "Aruaten"),
            WordTranslate("Close", "Isarado"),
            WordTranslate("Enter", "Sumrek"),
            WordTranslate("Exit", "Luwanen"),
            WordTranslate("Buy", "Gumatang"),
            WordTranslate("Sell", "Ibaligya"),
            WordTranslate("Give", "Ittod"),
            WordTranslate("Take", "Akmut"),
            WordTranslate("Ride", "Sumakay"),
            WordTranslate("Drive", "Agturay"),
            WordTranslate("Stop", "Tumungpal"),
            WordTranslate("Wait", "Agaud"),
            WordTranslate("Call", "Tawagan"),
            WordTranslate("Help", "Tulong"),
            WordTranslate("Bring", "Ibaybayad"),
            WordTranslate("Send", "Ipadala"),
            WordTranslate("Find", "Ikit"),
            WordTranslate("Lose", "Nakatnag"),
            WordTranslate("See", "Makita"),
            WordTranslate("Hear", "Denggen"),
            WordTranslate("Friendship", "Kakabsat"),
            WordTranslate("Work hard", "Agbasa nga napigsa"),
            WordTranslate("Forgive", "Patawaran"),
            WordTranslate("Respect", "Tulung"),
            WordTranslate("Help", "Agkuna"),
            WordTranslate("Brave", "Nalaylay"),
            WordTranslate("Joy", "Rag-o"),
            WordTranslate("Smile", "Ragragsak"),
            WordTranslate("Laugh", "Rangrang-ay"),
            WordTranslate("Freedom", "Silaw"),
            WordTranslate("Faith", "Pamati"),
            WordTranslate("Hope", "Tarigagay"),
            WordTranslate("Dream", "Damdamag"),
            WordTranslate("Success", "Balligi"),
            WordTranslate("Future", "Nabibiag"),
            WordTranslate("Leader", "Mangngaasi"),
            WordTranslate("Kind", "Naimbag"),
            WordTranslate("Peace", "Pakkarayan"),
            WordTranslate("Gift", "Regalo"),
            WordTranslate("Wisdom", "Namnama"),
            WordTranslate("Prayer", "Kararag"),
            WordTranslate("Believe", "Pammati"),
            WordTranslate("Honest", "Patik"),
            WordTranslate("Lucky", "Maliwawa"),
            WordTranslate("Hungry", "Mabisin"),
            WordTranslate("Thirsty", "Mayat"),
            WordTranslate("Busy", "Agtutukneng"),
            WordTranslate("Quiet", "Nabaknang"),
            WordTranslate("Rich", "Nabaliw"),
            WordTranslate("Poor", "Nalintag"),
            WordTranslate("Weak", "Nalaka"),
            WordTranslate("Strong", "Narabaw"),
            WordTranslate("Brave", "Nalaylay"),
            WordTranslate("Wise", "Nainsangayan"),
            WordTranslate("New", "Baro"),
            WordTranslate("Old", "Daang"),
            WordTranslate("Lucky", "Gambang"),
            WordTranslate("Foolish", "Agngas-ngas"),
            WordTranslate("Happy", "Nagsaya"),
            WordTranslate("Sad", "Liday"),
            WordTranslate("Excited", "Nabangkag"),
            WordTranslate("Bored", "Naliday"),
            WordTranslate("Afraid", "Buteng"),
            WordTranslate("Angry", "Agbuteng"),
            WordTranslate("Love", "Ayat"),
            WordTranslate("Hate", "Anghet"),
            WordTranslate("Lost", "Narawraw"),
            WordTranslate("Find", "Mangkit"),
            WordTranslate("Safe", "Nasingpet"),
            WordTranslate("Dangerous", "Mapanganib"),
            WordTranslate("Healthy", "Nasalun-at"),
            WordTranslate("Sick", "Aglawlaw"),
            WordTranslate("Clean", "Nasadiya"),
            WordTranslate("Dirty", "Napudaw"),
            WordTranslate("Strong", "Nangngeg"),
            WordTranslate("Weak", "Nalakay"),
            WordTranslate("Win", "Balligi"),
            WordTranslate("Lose", "Mapasak"),
            WordTranslate("Fight", "Pannakidangdang"),
            WordTranslate("Argue", "Pannakadungdan"),
            WordTranslate("Shy", "Nabagbag"),
            WordTranslate("Confident", "Napinpintas"),
            WordTranslate("Rich", "Baknang"),
            WordTranslate("Poor", "Matawa"),
            WordTranslate("Quick", "Napigsa"),
            WordTranslate("Slow", "Naludag"),
            WordTranslate("Smart", "Maipangpanggep"),
            WordTranslate("Dumb", "Naladaw"),
            WordTranslate("Hard", "Napudot"),
            WordTranslate("Soft", "Nalanglasi"),
            WordTranslate("Expensive", "Nabangsit"),
            WordTranslate("Cheap", "Nalaka"),
            WordTranslate("Tight", "Nakappu"),
            WordTranslate("Loose", "Nalukas"),
            WordTranslate("Empty", "Nangngeg"),
            WordTranslate("Full", "Nalunlun"),
            WordTranslate("Early", "Nasaapa"),
            WordTranslate("Late", "Nasalut"),
            WordTranslate("Bitter", "Napait"),
            WordTranslate("Sweet", "Nasam-it"),
            WordTranslate("Spicy", "Nagangsi"),
            WordTranslate("Salty", "Naasini"),
            WordTranslate("Sour", "Nasuam"),
            WordTranslate("Lazy", "Agtugot"),
            WordTranslate("Diligent", "Nagarbo"),
            WordTranslate("Generous", "Naimbag"),
            WordTranslate("Greedy", "Agtakaw"),
            WordTranslate("Polite", "Naimbag"),
            WordTranslate("Rude", "Agtartari"),
            WordTranslate("Hardworking", "Nagpudpudot"),
            WordTranslate("Loyal", "Nagserbi"),
            WordTranslate("Creative", "Mairuay"),
            WordTranslate("Curious", "Agkukulo"),
            WordTranslate("Honest", "Agtulnog"),
            WordTranslate("Patient", "Nabangsit"),
            WordTranslate("Brave", "Nalaylay"),
            WordTranslate("Calm", "Nasangpet")


        )
        return wordTranslations

}